### ISSUE TITLE
Source File as commandline argument

### ISSUE THREAD

**Issue by mdkling** [cornerStone-Dev/fith#2]
Currently, the fith binary is hard-coded to process all files matching the pattern `*.fith` in the directory `../fith_src`.  It would be nice to specify a file at runtime as a command line argument. Something along the lines of `$ fith script.fith`

**Comment by cornerStone-Dev** [comment]
Updated with this ability. Also compatible with -repl. This allows you to load a file as a starting point then use the repl to explore from there. Implementation is currently dirty, will clean up later.
