### ISSUE TITLE
REPL Environment

### ISSUE THREAD

**Issue by mdkling** [cornerStone-Dev/fith#4]
An interactive shell like `irb` in ruby or the python shell would be nice for rapid debugging and simple math operations.

**Comment by cornerStone-Dev** [comment]
I upgraded the command line interface with the -repl option to go into this mode. Note: functions and if else then statements have to be on one line for now.

1. ".exit" command will exit from the program
2. ".dump" will print all previously entered commands out to your terminal
3. ".save" will save all previously entered commands to a file session.fith
